# Generated by Discord Obfuscate on 2026-02-18

# Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("discord_obfuscate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordRoleObfuscation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opt_out",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, the original group name is used.",
                    ),
                ),
                (
                    "obfuscation_type",
                    models.CharField(
                        choices=[
                            ("sha256_hex", "SHA256 + hex"),
                            ("sha256_base32", "SHA256 + base32"),
                            ("blake2s_hex", "BLAKE2s + hex"),
                            ("blake2s_base32", "BLAKE2s + base32"),
                        ],
                        default="sha256_base32",
                        max_length=32,
                    ),
                ),
                (
                    "obfuscation_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Format string using {hash8}, {hash12}, {hash16}.",
                        max_length=120,
                    ),
                ),
                (
                    "divider_characters",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of divider characters.",
                        max_length=64,
                    ),
                ),
                (
                    "min_chars_before_divider",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum number of characters before a divider is used.",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If set, overrides the obfuscation method.",
                        max_length=100,
                    ),
                ),
                (
                    "role_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cached Discord role ID for rename operations.",
                        null=True,
                    ),
                ),
                (
                    "last_obfuscated_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_obfuscation",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord role obfuscation",
                "verbose_name_plural": "Discord role obfuscations",
                "ordering": ["group__name"],
            },
        ),
    ]
