# Generated by Discord Obfuscate on 2026-02-18

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0002_discordroleobfuscation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordObfuscateConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_on_save",
                    models.BooleanField(
                        default=True,
                        help_text="Queue a role rename task when a config is saved in admin.",
                    ),
                ),
                (
                    "periodic_sync_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable periodic full sync of roles via Celery beat.",
                    ),
                ),
                (
                    "periodic_sync_minute",
                    models.CharField(
                        default="0",
                        help_text="Cron minute field for periodic sync.",
                        max_length=32,
                    ),
                ),
                (
                    "periodic_sync_hour",
                    models.CharField(
                        default="*/1",
                        help_text="Cron hour field for periodic sync.",
                        max_length=32,
                    ),
                ),
                (
                    "periodic_sync_day_of_week",
                    models.CharField(
                        default="*",
                        help_text="Cron day_of_week field for periodic sync.",
                        max_length=32,
                    ),
                ),
                (
                    "periodic_sync_day_of_month",
                    models.CharField(
                        default="*",
                        help_text="Cron day_of_month field for periodic sync.",
                        max_length=32,
                    ),
                ),
                (
                    "periodic_sync_month_of_year",
                    models.CharField(
                        default="*",
                        help_text="Cron month_of_year field for periodic sync.",
                        max_length=32,
                    ),
                ),
                (
                    "periodic_sync_timezone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Timezone for periodic sync (blank uses project timezone).",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Obfuscate config",
            },
        ),
    ]
