# Generated by Discord Obfuscate on 2026-02-18

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0003_discordobfuscateconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, set Discord role color during sync.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color",
            field=models.CharField(
                default="#000000",
                help_text="Role color in hex (#RRGGBB).",
                max_length=7,
            ),
        ),
    ]
