# Generated by Discord Obfuscate on 2026-02-18

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0004_discordobfuscateconfig_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="role_color",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="role_color_enabled",
        ),
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="role_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional role color in hex (#RRGGBB).",
                max_length=7,
            ),
        ),
    ]
