# Generated by Discord Obfuscate on 2026-02-18

# Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0005_role_color_per_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discordobfuscateconfig",
            options={"verbose_name": "Discord Obfuscate Config"},
        ),
        migrations.AlterModelOptions(
            name="discordroleobfuscation",
            options={
                "ordering": ["group__name"],
                "verbose_name": "Discord Role Obfuscation",
                "verbose_name_plural": "Discord Role Obfuscations",
            },
        ),
        migrations.AlterField(
            model_name="discordroleobfuscation",
            name="last_obfuscated_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Obfuscated Name",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable periodic sync for role color rules.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_minute",
            field=models.CharField(
                default="0",
                help_text="Cron minute field for role color sync.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_hour",
            field=models.CharField(
                default="*/1",
                help_text="Cron hour field for role color sync.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_day_of_week",
            field=models.CharField(
                default="*",
                help_text="Cron day_of_week field for role color sync.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_day_of_month",
            field=models.CharField(
                default="*",
                help_text="Cron day_of_month field for role color sync.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_month_of_year",
            field=models.CharField(
                default="*",
                help_text="Cron month_of_year field for role color sync.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="role_color_rule_sync_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Timezone for role color sync (blank uses project timezone).",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="DiscordRoleColorRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Rule name shown in admin.",
                        max_length=100,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Role name pattern. Use * as a wildcard.",
                        max_length=150,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic color assignment for this rule.",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Match role names with case sensitivity.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers run first when multiple rules match.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord Role Color Rule",
                "verbose_name_plural": "Discord Role Color Rules",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscordRoleColorAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.BigIntegerField()),
                ("role_name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="discord_obfuscate.discordrolecolorrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Role Color Assignment",
                "verbose_name_plural": "Discord Role Color Assignments",
                "ordering": ["rule", "role_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="discordrolecolorassignment",
            constraint=models.UniqueConstraint(
                fields=("role_id",), name="unique_role_color_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="discordrolecolorassignment",
            constraint=models.UniqueConstraint(
                fields=("color",), name="unique_role_color_value"
            ),
        ),
    ]
