# Generated by Discord Obfuscate on 2026-02-19

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0006_role_color_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="use_random_key",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If enabled, obfuscation uses a random key instead of the group name. "
                    "Rotation tasks only apply to entries with this enabled."
                ),
            ),
        ),
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="random_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Random 16-character key used for obfuscation when enabled.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="random_key_rotate_name",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Allow the rotation task to rename this role. "
                    "Only applies when random key mode is enabled."
                ),
            ),
        ),
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="random_key_rotate_position",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Allow the rotation task to reposition this role. "
                    "Only applies when random key mode is enabled."
                ),
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable periodic rotation of random obfuscation keys.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_minute",
            field=models.CharField(
                default="0",
                help_text="Cron minute field for random key rotation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_hour",
            field=models.CharField(
                default="0",
                help_text="Cron hour field for random key rotation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_day_of_week",
            field=models.CharField(
                default="*",
                help_text="Cron day_of_week field for random key rotation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_day_of_month",
            field=models.CharField(
                default="*",
                help_text="Cron day_of_month field for random key rotation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_month_of_year",
            field=models.CharField(
                default="*",
                help_text="Cron month_of_year field for random key rotation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Timezone for random key rotation (blank uses project timezone).",
                max_length=64,
            ),
        ),
    ]
