# Generated by Discord Obfuscate on 2026-02-19

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0007_random_key_rotation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_minute",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_hour",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_day_of_week",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_day_of_month",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_month_of_year",
        ),
        migrations.RemoveField(
            model_name="discordobfuscateconfig",
            name="random_key_rotation_timezone",
        ),
    ]
