# Generated by Discord Obfuscate on 2026-02-19

# Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0008_random_key_rotation_opts"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordroleobfuscation",
            name="state_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="State name for state-based obfuscation.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="discordroleobfuscation",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discord_obfuscation",
                to="auth.group",
            ),
        ),
    ]
