# Generated by Discord Obfuscate on 2026-02-19

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_obfuscate", "0009_state_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Default opt-out for newly created entries.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_use_random_key",
            field=models.BooleanField(
                default=False,
                help_text="Default random key setting for newly created entries.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_random_key_rotate_name",
            field=models.BooleanField(
                default=True,
                help_text="Default rotate-name setting for new random-key entries.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_random_key_rotate_position",
            field=models.BooleanField(
                default=True,
                help_text="Default rotate-position setting for new random-key entries.",
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_obfuscation_type",
            field=models.CharField(
                choices=[
                    ("sha256_hex", "SHA256 + hex"),
                    ("sha256_base32", "SHA256 + base32"),
                    ("blake2s_hex", "BLAKE2s + hex"),
                    ("blake2s_base32", "BLAKE2s + base32"),
                ],
                default="sha256_base32",
                help_text="Default obfuscation type for new entries.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_divider_characters",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default divider characters for new entries.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="discordobfuscateconfig",
            name="default_min_chars_before_divider",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Default minimum chars before divider for new entries.",
            ),
        ),
    ]
